# Generated by Django 4.2.30 on 2026-06-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'geocode cache entry',
                'verbose_name_plural': 'geocode cache entries',
            },
        ),
        migrations.CreateModel(
            name='Truckstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('low_confidence', 'Low Confidence'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['state', 'city', 'canonical_name'],
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_trucks_state_1c4de4_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_trucks_latitud_98babf_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.PositiveIntegerField(db_index=True)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('source_row_hash', models.CharField(max_length=64, unique=True)),
                ('truckstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='fuel.truckstop')),
            ],
            options={
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['truckstop', 'retail_price'], name='fuel_fuelpr_truckst_dd6a9c_idx'), models.Index(fields=['rack_id'], name='fuel_fuelpr_rack_id_d1d1e1_idx')],
            },
        ),
    ]
